<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:xacro="http://ros.org/wiki/xacro"
  name="kurtana">

  <property name="M_PI" value="3.1415926535897931" />

  <!-- ******************** -->
  <!-- *** KURTana Rack *** -->
  <!-- ******************** -->
  
  <include filename="$(find kurt_description)/parts/kurtana_rack.urdf.xacro" />

  <property name="kinect_x_offset" value="0.025" />
  <property name="kinect_z_offset" value="0.087" />

  <!-- ************************ -->
  <!-- *** Microsoft Kinect *** -->
  <!-- ************************ -->
  
  <include filename="$(find kurt_description)/parts/kinect.urdf.xacro" />
  <xacro:kinect camera="kinect" />

  <joint name="kurtana_kinect_joint" type="fixed">
    <parent link="kurtana_pitchpole_link" />
    <child  link="kinect_link" />
    <origin xyz="${kinect_x_offset} 0 ${kinect_z_offset}" rpy="0 0 0"/>
  </joint>


  <!-- **************************** -->
  <!-- *** Neuronics Katana Arm *** -->
  <!-- **************************** -->

  <include filename="$(find katana_description)/urdf/katana_450_6m90a_with_controlbox.urdf.xacro" />

  <joint name="kurtana_baseplate_controlbox_joint" type="fixed">
    <origin xyz="0.05 0 ${baseplate_height*1.5}" rpy="0 0 0" />
    <parent link="kurtana_baseplate_link" />
    <child link="katana_internal_controlbox_link" />
  </joint>

</robot>
