<?xml version="1.0"?>
<robot
  xmlns:xacro="http://ros.org/wiki/xacro"
  name="rotunit">

  <include filename="$(find kurt_description)/common.xacro" />

  <include filename="$(find kurt_description)/parts/sick_lms200.urdf.xacro" />

  <xacro:property name="laser_rot_mount_x" value="0.18" />
  <xacro:property name="laser_rot_mount_y" value="0.18" />
  <xacro:property name="laser_rot_mount_z" value="0.143" />
  <xacro:property name="laser_rot_mount_mass" value="1.5" />

  <xacro:property name="harting_rot_x" value="0.05" />
  <xacro:property name="harting_rot_y" value="0.13" />
  <xacro:property name="harting_rot_z" value="0.06" />
  <xacro:property name="harting_rot_mass" value="0.2" />

  <link name="laser_rot_mount_link">
    <visual>
      <geometry>
        <box size="${laser_rot_mount_x} ${laser_rot_mount_y} ${laser_rot_mount_z}" />
      </geometry>
      <material name="silver" >
        <color rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${laser_rot_mount_x} ${laser_rot_mount_y} ${laser_rot_mount_z}" />
      </geometry>
    </collision>
    <xacro:box_inertial x="${laser_rot_mount_x}" y="${laser_rot_mount_y}" z="${laser_rot_mount_z}" mass="${laser_rot_mount_mass}" />
  </link>

  <joint name="laser_rot_joint" type="continuous">
    <parent link="laser_rot_mount_link" />
    <child link="laser" />
    <origin xyz="0 0 ${laser_rot_mount_z + 0.005}" rpy="${-M_PI/2} 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <link name="harting_rot_link">
    <visual>
      <geometry>
        <box size="${harting_rot_x} ${harting_rot_y} ${harting_rot_z}" />
      </geometry>
      <material name="silver" />
    </visual>
    <collision>
      <geometry>
        <box size="${harting_rot_x} ${harting_rot_y} ${harting_rot_z}" />
      </geometry>
    </collision>
    <xacro:box_inertial x="${harting_rot_x}" y="${harting_rot_y}" z="${harting_rot_z}" mass="${harting_rot_mass}" />
  </link>

  <joint name="harting_rot_joint" type="fixed">
    <parent link="laser_rot_mount_link" />
    <child link="harting_rot_link" />
    <origin xyz="${-laser_rot_mount_x/2 - harting_rot_x/2} 0 0" />
  </joint>
</robot>
